### ISSUE TITLE
bei pageset: bestehene page aus dashboard zum pageset hinzufügen

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/NIE-OS#111]
als alternative zur Möglichkeit, eine neue leere Page zu einem Pageset hinzuzufügen kann man auf der page-set-landing-page aus der liste der pages vom dashboard eine zum pageset hinzufügen

@nie-ine-sm zur info

**Comment by Vijeinath** [comment]
Dabei wird die Aktion aus dem Dashboard gelöscht ABER die dazugehörige Page nicht. Diese wird einfach beim Pageset angehängt. 
User darüber informieren a la: Die Page YYY gehört zur Aktion XXX, welche nun gelöscht wird. Die Page YYY ist dann nur noch über PageSet ZZZ erreichbar.

**Comment by janCstoffregen** [comment]
not relevant anymore bc the user can only create pageSets now.
