### ISSUE TITLE
Passwort - Kriterien

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/NIE-OS#178]
welche soll es geben? Gross, Kleinschreibung, Sonderzeichen, etc?

**Comment by ilinde** [comment]
ja und die Passwortlänge sollte mind. 9 Zeichen betragen.

**Comment by rfbaumgartner** [comment]
Zahlen auch noch

**Comment by janCstoffregen** [comment]
@rfbaumgartner hättest Du Lust, das zu machen?

**Comment by rfbaumgartner** [comment]
Einige Kriterien für Passwörter können jetzt überprüft werden:

- Kleinbuchstabe
- Grossbuchstabe
- Ziffer
- Sonderzeichen aus einer Liste
- Mind. 9 Zeichen.

Braucht es noch mehr?

**Comment by janCstoffregen** [comment]
super, danke! funktioniert alles hervorragend!

**Comment by janCstoffregen** [comment]
Wie angesprochen bitte zentralisieren zu einem Service, bitte in neuem Ordner

user-action-engine/shared

**Comment by janCstoffregen** [comment]
danke!!!
