### ISSUE TITLE
Data chooser: JSON Response not mappable/selectable; procedural issues

### ISSUE THREAD

**Issue by domsteinbach** [nie-ine/NIE-OS#180]
### I. JSON Response not mappable/selectable

**Using the [answer_JSON.txt](https://github.com/nie-ine/NIE-OS/files/2836369) the nodes/values are not selectable/mappable by the data chooser**

**issue arising:**
There is no query selectable in the data chooser drop down box.

**Reproduce by:**
- open a page
- Add a textlist viewer, reposition it, save page
- open data management
- open mapping for textlist viewer and map to the node bindings -> authorsname -> value; save, close data management
- Select the results bindings to the same node -> authorsname
- save, close
- in the page add a data chooser

### II. Further procedural issues
There are two further issues arising after saving/not saving a freshly added blank data chooser. 

**1.) Freezed loading page after saving an undefined data chooser**

The following procedure ends in a loop like forever loading window:

- add data chooser to the page
- leave the data chooser dropdownbox unselected  (not choosing a Query within data chooser)
- save the page with the blank data chooser
- open the Page data management

--> issue arising: Freeze in loading window.

**2) the "results binding value" in the page data management will be unselected/blanked out 
after adding a data chooser to a page and NOT saving the page**

- Open Page Data Management
- map a textlist viewer
- select a results binding value
- save, close
- add a data chooser but don't select a query
- save the page with the blank data chooser
- reopen the Page Data Management

--> issue arising: The once selected and saved results binding value gets unselected.

**Comment by janCstoffregen** [comment]
fixed
