### ISSUE TITLE
Enable aggregated data as data source for an app (whole JSON, JSON objects)

### ISSUE THREAD

**Issue by domsteinbach** [nie-ine/NIE-OS#206]
### 1. Context
At the moment only single keys of a JSON response can be mapped to the apps and only single key/value pairs are then passed via the data chooser for displaying them in the app. 

### 2. Requirements
For certain use cases there is need for mapping more complex/aggregated data to an app. Such use cases requiring aggregated data are for example:

- results list/table for a generic search
- index page
- data visualization (charts, graphs)
- third party apps/project specific apps with more complex requirements

### 3. Request for enhancement
As enhancement the following should be enabled (priority is top down):

**query-appp interface**
- [x] pass one complete JSON object with all its keys/values to an app
- [x] pass an array of JSON objects with all their keys/values to an app (may be the whole JSON response from an endpoint)

**query-app-mapping**
- [x] map a JSON object in the query-app-mapping to an app
- [x] map an entire JSON response of a query to an app

**results bindings and behaviour of the data chooser**
- [ ] it should be able to define a whole object (JSON object) as iterated instance in resource binding so the data chooser iterates through whole objects and dates up the app.
- [ ] There is still need to define a resource binding as the key/value which populates the data chooser. For example all vars "authorsname" should be displayed in the data chooser. Choosing one of theese authorsname should provide the whole JSON object to which the chosen "authorsname" belongs. 
- [ ]  it should be also able to define no iteration/resource binding at all so the whole JSON response will be passed to the app.

### 4. Example
The following file is containing the JSON response of the query "SPARQL TEST Lombardus" in NIE-OS. 
[agg_data_JSON.txt](https://github.com/nie-ine/NIE-OS/files/2905546/agg_data_JSON.txt)

**Comment by janCstoffregen** [comment]
Hi @domsteinbach, ich fang dann jetzt mit dieser Story an

**Comment by janCstoffregen** [comment]
Hi, the first 4 points are working now I think, when do you have time for talky?

For the other 3 points I need to understand it a little bit more still.

**Comment by janCstoffregen** [comment]
done bis auf widerruf
