### ISSUE TITLE
Replace Image Viewer --> not with nie-ine module anymore

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/NIE-OS#217]
Dear Reto,
since I have not kept the nie-ine module up to date, I had to take it out of NIE-OS. Thus, I had to outcomment the image - viewer in the page, because I used the one from the npm - module. Would you mind replacing it with the image viewer that is directly located in NIE-OS?

I'll post the lines in a second

Thank you!!

**Comment by janCstoffregen** [comment]
src/app/app-engine/page/page/page.component.html

zeile 464 und folgend --> I think you just have to replace the selector, right?

**Comment by rfbaumgartner** [comment]
Not so easy anymore. The input has been simplified.
What has to be changed in `openAppsInThisPage`?

**Comment by janCstoffregen** [comment]
which input has been simplified?

**Comment by rfbaumgartner** [comment]
simplified and complicated again (constructor...):

- ~image~ (SIPI format)
- add `iiifImagePath`
- add `maxImageWidth`
- add `maxImageHeight`

These inputs follow osd logic and not sipi logic.

**Comment by janCstoffregen** [comment]
which key/value pair is it from a knora -. image response?

**Comment by rfbaumgartner** [comment]
- iiifImagePath corresponds to knora-api:fileValueAsUrl
- maxImageWidth corresponds to knora-api:stillImageFileValueHasDimX
- maxImageHeight corresponds to knora-api:stillImageFileValueHasDimY

is that what you mean?

**Comment by janCstoffregen** [comment]
funktioniert, danke!

done
