### ISSUE TITLE
Tree Navigation ATH/LBD

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/NIE-OS#220]
@janCstoffregen @rfbaumgartner machen das zusammen

klickbarer baum, mit iri und type als output

http://localhost:4200/page?actionID=5c9b3de56152c1001e2fef8e&page=5c9b3e326152c1001e2fef91

**Comment by janCstoffregen** [comment]
die ID updated ein parameter in der url

**Comment by rfbaumgartner** [comment]
alternativer Ansatz zu IRI und Type: Kann auf jeder Ebene die gewählte IRI mit einem Parameter assoziiert werden (depth1, depth2, ...)? Dann kann bei den meisten Construct-Abfragen der Typ übersprungen werden und dafür das Vorhandensein der Paramter-Keys genutzt werden.

Als Nebeneffekt kann der Navigationsbaum auch aus der URL lesen und die gewählten Punkte markieren (wie routerLinkActive).

**Comment by janCstoffregen** [comment]
@rfbaumgartner @domsteinbach story ist in diesem sprint

**Comment by janCstoffregen** [comment]
@rfbaumgartner @domsteinbach gibt es hierzu eine Youtrack - story? Dann ändere ich den Titel, dann weiss ich, zu wem das gehört.

**Comment by rfbaumgartner** [comment]
Eine erste Version ist ja bereits vorhanden, die mit einer Antwort als JSON-LD rechnet. Bei grossen Hierarchiestrukturen in Projekten kann man aber nicht mit einer einzigen Abfrage alles abdecken.
Deshalb schlage ich vor, die Komponente umzubauen (oder zu ersetzen) mit einem Ansatz, der aufeinander folgende Abfragen und Paginierung unterstützt.

Statt einer einzelnen Hierarchie als Input kann eine Ressourcen-IRI angegeben werden. Der Aufbau der Hierarchie im `CONSTRUCT` der bisherigen Abfrage kann durch ein Array von Properties ersetzt werden, die die Verbindungen vom Root-Element her die einzelnen Verbindungen zu den Kindern beschreibt. 

Wie bisher soll die Navigation durch die Query-Parameter initialisiert werden können.

Als mögliche Verfeinerung kann zwischen Ausklappen und Auswählen unterschieden werden, gleichzeitig aber beim Einklappen der gewählte Pfad verkürzt werden.

**Comment by rfbaumgartner** [comment]
Erledigt mit #304
