### ISSUE TITLE
 Funktion "Passwort vergessen" für E-Mail-Adressen ohne Account 

### ISSUE THREAD

**Issue by contra8** [nie-ine/NIE-OS#245]
1. Aufruf der Seite https://nieos.nie-ine.ch/home
2. Eintrag einer E-Mail-Adresse, zu der kein Account existiert
3. Klicken auf "Passwort vergessen"
4. Klicken auf "SEND EMAIL"
5. Meldung erscheint: "You will get an Email with a Link to restore your password"

Meldung sollte eher lauten: "Zu dieser E-Mail-Adresse existiert kein Account"

**Comment by janCstoffregen** [comment]
done
