### ISSUE TITLE
data-list-view

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/NIE-OS#247]
First: port - forwarding & allow cors

```typescript
      else {
        this.dataService.getData().subscribe(data => {
          console.log( data, this.resData2 );
          // this.resData = data;
          // this.table.renderRows();
        });
        this.resData = this.resData2;
      }
    }
```

@domsteinbach

**Comment by janCstoffregen** [comment]
table should update

**Comment by janCstoffregen** [comment]
@domsteinbach habe nun einiges verändert, ich glaube, das problem nun ist, dass das resultat so gross ist, könntest Du den Query vielleicht so ändern, dass der Resultat - Array kleiner Ausfällt? :)

Habe im html zeilen 18 und 20 auskommentiert, ich glaube, es funktioniert nun auch mit dem query, wenn die response wie gesagt kleiner ist, bitte schau mal in den commit von eben #247

**Comment by janCstoffregen** [comment]
würde gern zusammen mit Dir den angepassten Code anschauen!

**Comment by domsteinbach** [comment]
let's go for it :-)

**Comment by janCstoffregen** [comment]
closed for now
