### ISSUE TITLE
Texteingabebox verschwindet

### ISSUE THREAD

**Issue by contra8** [nie-ine/NIE-OS#250]
1. Einloggen
2. Runterscrollen bis zur Texteingabebox "Ihre Nachricht"
3. Oben rechts klicken auf "Einstellungen"
4. Overlay erscheint
5. Texteingabebox verschwindet

Beispielfilm:
https://www.dropbox.com/s/52jbw9c38fsrf2d/2019-04-25%2014.07.30.mp4?dl=0

**Comment by janCstoffregen** [comment]
voll super mit dem Film, danke, ich wusste vorher nicht, wann das Feld verschwindet!

**Comment by janCstoffregen** [comment]
done
