### ISSUE TITLE
Passwortwiederholung beim Registrieren

### ISSUE THREAD

**Issue by contra8** [nie-ine/NIE-OS#252]
Wenn man https://nieos.nie-ine.ch/register aufruft und sich registrieren möchte, muss man das gewählte Passwort nur einmal eingeben. Da der benutzenden Person das Passwort nicht angezeigt wird, hat sie keine Kontrolle, ob sie ihr Wunschpasswort korrekt eingegeben hat.

Ein Feld zur erneuten Eingabe des Passworts wäre hilfreich. Beim Passortwechsel gibt es dieses Feld (siehe Menüpunkt "Einstellungen" --> Tab "Passwort"

![2019-04-26_ScreenshotRegistrierung](https://user-images.githubusercontent.com/19752490/56800932-874f3980-681c-11e9-94fc-86edbca1f2f2.jpg)

![2019-04-26_ScreenshotPasswortwechsel](https://user-images.githubusercontent.com/19752490/56800930-874f3980-681c-11e9-8378-8a9a5c6aec1b.jpg)

**Comment by janCstoffregen** [comment]
man kann sein passwort mit email wiederherstellen, deswegen werde ich dies nicht mehr machen.
