### ISSUE TITLE
Dashboard: Mauszeiger-Typ auf aktiven Flächen

### ISSUE THREAD

**Issue by contra8** [nie-ine/NIE-OS#253]
Im Dashboard unter https://nieos.nie-ine.ch/dashboard gibt es grossflächige Icons wie "Neue Aktion" (grünes Quadrat mit Plus-Symbol in der Mitte). Diese sehen nach interaktiven Elementen aus. Fährt man mit dem Mauszeiger über die Elemente, bleibt der Mauszeiger ein Pfeil und man denkt sich automatisch: "Wenn dieses Icon nicht interaktiv ist, wo muss ich dann klicken?"

Also versucht man es mit der Schrift unterhalb der Icons, und diese ist ebenfalls nicht interaktiv. Man merkt erst dann: "Oh, das Icon ist doch interaktiv."

Ein Mauszeiger wie bei Buttons (Hand mit ausgestrecktem Zeigefinger) könnte hier die Interaktion deutlich beschleunigen.

**Comment by janCstoffregen** [comment]
danke, ist viel besser so, hab's gemacht
