### ISSUE TITLE
Login-Seite: Haken vor "Passwort vergessen" ändert nur bei jedem 2. Klick

### ISSUE THREAD

**Issue by contra8** [nie-ine/NIE-OS#255]
1. Seite https://nieos.nie-ine.ch/home aufrufen
2. Klick auf "Passwort vergessen" -> Haken taucht in Kästchen links auf -> OK
3. Nochmaliger Klick auf "Passwort vergessen" -> Haken verschwindet nicht -> NOK
4. Nochmaliger Klick auf "Passwort vergessen" -> Haken verschwindet -> NOK
5. Nochmaliger Klick auf "Passwort vergessen" -> Haken bleibt verschwunden -> OK
6. Nochmaliger Klick auf "Passwort vergessen" -> Haken erscheint -> OK
7. Beliebig oft wiederholbar

Zum besseren Verständnis siehe Video:
https://www.dropbox.com/s/dp7kw9u534yjsl5/2019-04-26%2023.46.22.mp4?dl=0

**Comment by janCstoffregen** [comment]
done

**Comment by contra8** [comment]
Problem besteht nach wie vor.

**Comment by janCstoffregen** [comment]
ok, hab jetzt aus der checkbox einen button gemacht, mit dem neuen label toBeTested findet man später die issues, die man testen soll, hab ich gerade hinzugefügt

**Comment by contra8** [comment]
Ich werds dann testen.

**Comment by janCstoffregen** [comment]
ok, danke!

**Comment by janCstoffregen** [comment]
bitte testen und schliessen: https://nieos.nie-ine.ch/home

**Comment by janCstoffregen** [comment]
done
