### ISSUE TITLE
Continue with table

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/NIE-OS#263]
@domsteinbach

**Comment by domsteinbach** [comment]
I am currently on refactoring (splitting up in several components/separation of concerns), fixing features such as paginator, sorting asf. and make it customizable by the stored settings. I get back to you soon.

**Comment by janCstoffregen** [comment]
ok, thank you!

**Comment by domsteinbach** [comment]
@janCstoffregen : the Inputs are changed. There are three different inputs needed:
 
- Input() queryResponse: any; // --> the mapped and passed JSON response of a query in NieOS page data management (could be static JSON defined in data mgmnt or the result of a query)
- Input() settings: any; // the settings stored in mongodb defined and mapped via page data management. 
- Input() query: any; // --> just a string containing a query or an object containing several infos. This will be implemented later I guess. This should be passed from other components/apps.

**Comment by janCstoffregen** [comment]
> * Input() query: any; // --> just a string containing a query or an object containing several infos. This will be implemented later I guess. This should be passed from other components/apps.

can this be passed over the url?

**Comment by domsteinbach** [comment]
Yes, in most cases. It can be ignored for now. (There might be cases where this may not be a proper solution)

**Comment by domsteinbach** [comment]
Here is a simple query to try:
Headers: 'Content-Type':  'application/sparql-results+json;charset=UTF-8'

`http://localhost:8080/repositories/knora-test?PREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20knora-base%3A%20%3Chttp%3A%2F%2Fwww.knora.org%2Fontology%2Fknora-base%23%3E%0APREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX%20drcs%3A%20%3Chttp%3A%2F%2Fwww.knora.org%2Fontology%2F0046%2Fdrcs%23%3E%0APREFIX%20human%3A%20%3Chttp%3A%2F%2Fwww.knora.org%2Fontology%2F0048%2Fhuman%23%3E%0APREFIX%20text%3A%20%3Chttp%3A%2F%2Fwww.knora.org%2Fontology%2Fshared%2Ftext%23%3E%0APREFIX%20kuno-raeber%3A%20%3Chttp%3A%2F%2Fwww.knora.org%2Fontology%2F004D%2Fkuno-raeber%23%3E%0A%0ASELECT%09%3Findexed_thing%20%3Flabel%20%3Ftype%20%3Fcomment%0A%0AWHERE%20%09%7B%3Findexed_thing%20%3Fsomeprop%20text%3AText%20.%0A%20%20%20%20%09%3Findexed_thing%20rdfs%3Alabel%20%3Flabel.%0A%20%20%20%20%20%20%20%20OPTIONAL%20%7B%3Findexed_thing%20rdf%3Atype%20%3Ftype.%0A%20%20%20%20%20%20%20%20%09%09%20%20%3Ftype%20rdfs%3Acomment%20%3Fcomment.%0A%20%20%20%20%20%20%20%20%20%20%20%20%09%09%09%7D%0A%20%20%20%20%09%7D%0A%20limit%20500`

**decoded it is:**

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX drcs: <http://www.knora.org/ontology/0046/drcs#>
PREFIX human: <http://www.knora.org/ontology/0048/human#>
PREFIX text: <http://www.knora.org/ontology/shared/text#>
PREFIX kuno-raeber: <http://www.knora.org/ontology/004D/kuno-raeber#>

SELECT	?indexed_thing ?label ?type ?comment

WHERE 	{?indexed_thing ?someprop text:Text .
    	?indexed_thing rdfs:label ?label.
        OPTIONAL {?indexed_thing rdf:type ?type.
        		  ?type rdfs:comment ?comment.
            			}
    	}
 limit 500

**Comment by janCstoffregen** [comment]
I think the only problem in the end is how to connect from NIE-OS to the triple - store while the triplestore does not have an exposed api, right?

**Comment by domsteinbach** [comment]
> I think the only problem in the end is how to connect from NIE-OS to the triple - store while the triplestore does not have an exposed api, right?

Yes, imho that should be the only issue to solve. (except configuration of data management and/or app communication via url asf.)

**Comment by janCstoffregen** [comment]
so, can I deploy a triple store, open to the public for published data?

**Comment by janCstoffregen** [comment]
ok, I'll implement it this way then.

**Comment by janCstoffregen** [comment]
works pretty well, I'll close it for now
