### ISSUE TITLE
Add default input to SVG-Transkription

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/NIE-OS#288]
like I did in the textlist Viewer

**Comment by janCstoffregen** [comment]
and for avpEditionView

**Comment by janCstoffregen** [comment]
and for the app-image-with-overlay

**Comment by janCstoffregen** [comment]
and for the tree navigation

**Comment by rfbaumgartner** [comment]
The future of avpEditionView is pending and therefore it is too early for a default input.

**Comment by janCstoffregen** [comment]
ok, I set this to done
