### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by afa-unibas** [nie-ine/NIE-OS#68]
https://choosealicense.com/ ;)

**Comment by janCstoffregen** [comment]
Danke für den Anstoss, ich warte auf Antwort.. sollte in der nächsten Woche klar sein.. ist komplizierter als ich dachte..

**Comment by janCstoffregen** [comment]
@ilinde

**Comment by janCstoffregen** [comment]
@ilinde können wir vielleicht schon ein zwischenzeitiges nun definieren?

**Comment by ilinde** [comment]
Um es nicht unnötig spannend zu machen: Ich habe mit Melanie G. (CC digital law) geklärt, ob/wer in unserem Fall überhaupt eine Lizenz vergeben darf (Urheberrechtsanmassung ist strafbar und wenn das Produkt im Auftrag eines Arbeitgebers entsteht, kann es kompliziert werden. Dazu mehr beim EWTR am 05.11.).
Beim EWTR können wir dann genauer klären, welche Lizenz wir wählen. Nach den Gesprächen mit Melanie, würde ich die MIT oder BSD2clause empfehlen. Denkbar wäre auch die GNU-GPL (share alike). 
Das DaSCH hat die sehr restriktive GNU-A-GPL (non commercial, share alike), die imho einige Hürden bei der Nachnutzung mit sich bringt.
Und wegen der Datenschutzerklärung: Ich werde versuchen Mitte November einen Termin mit der Datenschutzbeauftragten zu bekommen. Dann würde ich ihr gerne einen ersten Entwurf zur Besprechung vorlegen. @janCstoffregen  kannst du mir eine Einschätzung geben, warum es sinnvoll sein könnte, Nutzerdaten nicht zu löschen, wenn sie ihren Account gelöscht haben (sofern sie noch nicht über das nieOS publiziert haben)?

**Comment by janCstoffregen** [comment]
ich habe noch nicht weiter drüber nachgedacht, bzgl löschen user accounts, von mir aus können wir es gern einfach löschen. 

Bei einer Veröffentlichung von pages und Pagesets sollten wir aber sichergehen, dass diese dann nicht mehr gelöscht werden sollten, bzw wir sollten drüber nachdenken, was das für Konsequenzen hat, wenn man etwas veröffentlicht.

**Comment by janCstoffregen** [comment]
done
