### ISSUE TITLE
Implement feedback form

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/NIE-OS#81]
with nodejs

**Comment by janCstoffregen** [comment]
done

**Comment by lukashilgert** [comment]
text input is barely readable
<img width="1042" alt="Bildschirmfoto 2019-04-24 um 11 01 08" src="https://user-images.githubusercontent.com/16624074/56646674-4b7f6d00-6680-11e9-9f55-112f9e359471.png">

**Comment by janCstoffregen** [comment]
done
